language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libssl1.0.0

install:
  - python setup.py install

before_script:
  - pip install unittest2
  - pip install mock
  - pip install vcrpy
  - pip install cryptography

script:
  - python setup.py test

matrix:
  allow_failures:
    - python: pypy

sudo: false
