orbs: # declare what orbs we are going to use
    node: circleci/python@1.5.0

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

jobs:
    build:
        working_directory: ~/repo

        # Primary container image where all commands run

        docker:
            - image: circleci/python:3.5.7  # primary container for the build job
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD

        steps:
            - checkout
            - run: 
                  name: Install Dependencies
                  command: |  # use pipenv to install dependencies
                    sudo pip install pipenv
                    pipenv install
                    
            - run: 
                  name: Install goShippo
                  command: pipenv run python setup.py install
            - run: 
                  name: Test
                  command: pipenv run python -W always setup.py test
